import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  /* name, description, host */

  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [host, setHost] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    const data = {
      name,
      description,
      host,
    };
    await axios.post("/api/client", data);
    window.location.href = "/";
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mt-3 ${styles.main} ${inter.className}`}>
        <div className="row justify-content-between">
          <h3>Create client</h3>
          <div className="col-auto"></div>
        </div>

        {/* form */}
        <form className="row g-3" onSubmit={(e) => handleSubmit(e)}>
          {/* name, description, host */}
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              className="form-control"
              id="name"
              onChange={(e) => setName(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label htmlFor="description">Description</label>
            <input
              type="text"
              className="form-control"
              id="description"
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label htmlFor="host">Host</label>
            <input
              type="text"
              className="form-control"
              id="host"
              onChange={(e) => setHost(e.target.value)}
            />
          </div>

          <div className="">
            <button type="submit" className="btn btn-primary">
              Create
            </button>
          </div>
        </form>
      </main>
    </>
  );
}
