import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);

  useEffect(() => {
    axios.get("/api/client").then((res) => {
      setData(res.data);
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mt-3 ${styles.main} ${inter.className}`}>
        <div className="d-flex justify-content-between">
          <h3>clients</h3>
          <div className="col-auto">
            <a href="/create" className="btn btn-primary">
              Create
            </a>
          </div>
        </div>

        <table className="table table-striped">
          <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">name</th>
              <th scope="col">description</th>
              <th scope="col">host</th>
              <th scope="col">createdAt</th>
              <th scope="col">action</th>
            </tr>
          </thead>
          <tbody>
            {data.map((item, key) => (
              <tr key={item._id}>
                <th scope="row">{key + 1}</th>
                <td>{item.name}</td>
                <td>{item.description}</td>
                <td>{item.host}</td>
                <td>{item.createdAt}</td>
                <td>
                  <a href={`/users/${item._id}`} className="btn btn-primary">
                    Users
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
}
