import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(false);
  const [ask2fa, setAsk2fa] = useState(false);
  const [token, setToken] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post("/api/login", {
        email,
        password,
        token,
      });
      if (res.data?.multifactorEnabled) {
        setAsk2fa(true);
      } else {
        localStorage.setItem("token", res.data?.token);
        window.location.href = "/success";
      }
    } catch (error) {
      setError(error?.response?.data?.message || "Something went wrong");
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mt-3 ${styles.main} ${inter.className}`}>
        <div className="h-100">
          <div className="row justify-content-center">
            <div className="col-6 shadow p-3 mb-5 bg-white rounded">
              <h3>Login</h3>
              {error && (
                <div className="alert alert-danger" role="alert">
                  {error}
                </div>
              )}

              <form onSubmit={handleSubmit}>
                <div className="mb-3">
                  <label htmlFor="email" className="form-label">
                    Email address
                  </label>
                  <input
                    type="email"
                    className="form-control"
                    id="email"
                    aria-describedby="emailHelp"
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </div>
                <div className="mb-3">
                  <label htmlFor="password" className="form-label">
                    Password
                  </label>
                  <input
                    type="password"
                    className="form-control"
                    id="password"
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </div>
                {ask2fa && (
                  <div className="mb-3">
                    <label htmlFor="token" className="form-label">
                      2FA Token
                    </label>
                    <input
                      type="text"
                      className="form-control"
                      id="token"
                      onChange={(e) => setToken(e.target.value)}
                    />
                  </div>
                )}
                <button type="submit" className="btn btn-primary">
                  Submit
                </button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
