import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import QR from "@/components/qr";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState([]);

  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    axios.get("/api/users/?client_id=" + id).then((res) => {
      setData(res.data);
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mt-3 ${styles.main} ${inter.className}`}>
        <div className="d-flex justify-content-between">
          <h3>Users</h3>
          <div className="col-auto">
            <a
              href={`/users/create?client_id=${id}`}
              className="btn btn-primary"
            >
              Create
            </a>
          </div>
        </div>

        <table className="table table-striped">
          <thead>
            <tr>
              <th scope="col">id</th>
              <th scope="col">email</th>
              <th scope="col">firstName</th>
              <th scope="col">lastName</th>
              <th scope="col">action</th>
            </tr>
          </thead>
          <tbody>
            {data.map((item, key) => (
              <tr key={item._id}>
                <th scope="row">{item._id}</th>
                <td>{item.email}</td>
                <td>{item.firstName}</td>
                <td>{item.lastName}</td>
                <td>
                  <QR id={item._id} qr={item.qrCode} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </>
  );
}
