import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  /* firstName, lastName, email, password */

  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();

    // get client_id from url params
    const urlParams = new URLSearchParams(window.location.search);
    const client_id = urlParams.get("client_id");
    const data = {
      client_id,
      firstName,
      lastName,
      email,
      password,
    };
    await axios.post("/api/users", data);
    window.location.href = "/users/" + client_id;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container mt-3 ${styles.main} ${inter.className}`}>
        <div className="row justify-content-between">
          <h3>Create client</h3>
          <div className="col-auto"></div>
        </div>

        {/* form */}
        <form className="row g-3" onSubmit={(e) => handleSubmit(e)}>
          {/* first name, last name, email, password */}
          <div className="form-group">
            <label htmlFor="first_name">First Name</label>
            <input
              type="text"
              className="form-control"
              id="first_name"
              onChange={(e) => setFirstName(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label htmlFor="last_name">Last Name</label>
            <input
              type="text"
              className="form-control"
              id="last_name"
              onChange={(e) => setLastName(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              className="form-control"
              id="email"
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              type="text"
              className="form-control"
              id="password"
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          <div className="">
            <button type="submit" className="btn btn-primary">
              Create
            </button>
          </div>
        </form>
      </main>
    </>
  );
}
